name: Test

on:
  push:
    branches: [ "main", "*dev", "ci*" ]
  pull_request:
    branches: [ "main", "*dev" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        save-if: always()

    - name: Run tests
      run: cargo test --workspace --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        save-if: always()

    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: Check formatting
      run: cargo fmt --all --check

  # Disabled: Use simple-example-test.yml for cross-platform testing
  # macos_test:
  #   name: MacOS Tests
  #   runs-on: macos-13
  #   timeout-minutes: 20
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: cargo build --verbose
  #   - name: Run tests
  #     run: cargo test --verbose -- --test-threads 1

